In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv("Dataa.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Cerah' 'Tidak' 85.0 85.0]
 ['Cerah' 'Ya' 90.0 80.0]
 ['Mendung' 'Tidak' 78.0 83.0]
 ['Hujan' 'Tidak' 96.0 70.0]
 ['Hujan' 'Tidak' nan 68.0]
 ['Hujan' 'Ya' 70.0 65.0]
 ['Mendung' 'Ya' 65.0 64.0]
 ['Cerah' 'Tidak' 95.0 72.0]
 ['Cerah' 'Tidak' 70.0 69.0]
 ['Hujan' 'Tidak' 80.0 75.0]
 ['Cerah' 'Ya' 70.0 nan]
 ['Mendung' 'Ya' 90.0 72.0]
 ['Mendung' 'Tidak' 75.0 81.0]
 ['Hujan' 'Ya' 80.0 71.0]
 ['Hujan' 'Tidak' 65.0 78.0]]


In [ ]:
print(y)

['Tidak' 'Tidak' 'Ya' 'Ya' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya'
 'Ya' 'Tidak' 'Ya']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 2:4])
x[:, 2:4] = imputer.transform(x[:, 2:4])

In [ ]:
print(x)

[['Cerah' 'Tidak' 85.0 85.0]
 ['Cerah' 'Ya' 90.0 80.0]
 ['Mendung' 'Tidak' 78.0 83.0]
 ['Hujan' 'Tidak' 96.0 70.0]
 ['Hujan' 'Tidak' 79.21428571428571 68.0]
 ['Hujan' 'Ya' 70.0 65.0]
 ['Mendung' 'Ya' 65.0 64.0]
 ['Cerah' 'Tidak' 95.0 72.0]
 ['Cerah' 'Tidak' 70.0 69.0]
 ['Hujan' 'Tidak' 80.0 75.0]
 ['Cerah' 'Ya' 70.0 73.78571428571429]
 ['Mendung' 'Ya' 90.0 72.0]
 ['Mendung' 'Tidak' 75.0 81.0]
 ['Hujan' 'Ya' 80.0 71.0]
 ['Hujan' 'Tidak' 65.0 78.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0,1])], remainder="passthrough" )
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 1.0 0.0 85.0 85.0]
 [1.0 0.0 0.0 0.0 1.0 90.0 80.0]
 [0.0 0.0 1.0 1.0 0.0 78.0 83.0]
 [0.0 1.0 0.0 1.0 0.0 96.0 70.0]
 [0.0 1.0 0.0 1.0 0.0 79.21428571428571 68.0]
 [0.0 1.0 0.0 0.0 1.0 70.0 65.0]
 [0.0 0.0 1.0 0.0 1.0 65.0 64.0]
 [1.0 0.0 0.0 1.0 0.0 95.0 72.0]
 [1.0 0.0 0.0 1.0 0.0 70.0 69.0]
 [0.0 1.0 0.0 1.0 0.0 80.0 75.0]
 [1.0 0.0 0.0 0.0 1.0 70.0 73.78571428571429]
 [0.0 0.0 1.0 0.0 1.0 90.0 72.0]
 [0.0 0.0 1.0 1.0 0.0 75.0 81.0]
 [0.0 1.0 0.0 0.0 1.0 80.0 71.0]
 [0.0 1.0 0.0 1.0 0.0 65.0 78.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 1.0 0.0 78.0 83.0]
 [1.0 0.0 0.0 0.0 1.0 70.0 73.78571428571429]
 [0.0 1.0 0.0 1.0 0.0 79.21428571428571 68.0]
 [1.0 0.0 0.0 0.0 1.0 90.0 80.0]
 [0.0 1.0 0.0 0.0 1.0 80.0 71.0]
 [1.0 0.0 0.0 1.0 0.0 85.0 85.0]
 [0.0 1.0 0.0 1.0 0.0 65.0 78.0]
 [0.0 1.0 0.0 1.0 0.0 80.0 75.0]
 [1.0 0.0 0.0 1.0 0.0 70.0 69.0]
 [0.0 0.0 1.0 1.0 0.0 75.0 81.0]
 [0.0 0.0 1.0 0.0 1.0 90.0 72.0]
 [0.0 1.0 0.0 0.0 1.0 70.0 65.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 1.0 0.0 96.0 70.0]
 [1.0 0.0 0.0 1.0 0.0 95.0 72.0]
 [0.0 0.0 1.0 0.0 1.0 65.0 64.0]]


In [ ]:
print(y_train)

[1 1 1 0 0 0 1 1 1 1 1 0]


In [ ]:
print(y_test)

[1 0 1]
